# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"

  [context.production.environment]
    NODE_ENV = "production"
    CI = "false" # Отключаем режим CI, чтобы убрать лимиты по времени и ресурсам

[build.environment]
  CI = "false" # Отключаем режим CI для других контекстов

[build.lifecycle]
  ignore = ["*.js", "*.jsx"] # Игнорируем файлы, чтобы избежать завершения сборки из-за предупреждений

[[plugins]]
  package = "@netlify/plugin-nextjs"
