# Пример базового файла netlify.yml

# Базовые настройки
site:
  name: ci-cd-test
  build:
    command: npm run build # Команда сборки вашего проекта
  publish: dist/ # Каталог, из которого будет развертываться ваш сайт

# Дополнительные настройки (при необходимости)
# ...

# Настройки хуков (например, при успешном развертывании)
# ...
